changed policy due to deprecation

diff --git a/services/playbooks/roles/rabbitmq/templates/05-policy-job.yml.j2 b/services/playbooks/roles/rabbitmq/templates/05-policy-job.yml.j2
--- a/services/playbooks/roles/rabbitmq/templates/05-policy-job.yml.j2
+++ b/services/playbooks/roles/rabbitmq/templates/05-policy-job.yml.j2
@@ -33,11 +33,14 @@ spec:
             - |
               echo "RabbitMQ is up. Applying quorum queue policy..."
               rabbitmqctl --longnames -n rabbit@rabbitmq-0.rabbitmq-headless.{{ rabbitmq_namespace }}.svc.cluster.local \
-                --apply-to queues \
                 set_policy {{ rabbitmq_ha_policy_name }} \
                 "{{ rabbitmq_ha_policy_pattern }}" \
-                '{{ rabbitmq_ha_policy_definition }}'
-
-              echo "Policy applied successfully!"
+                '{{ rabbitmq_ha_policy_definition }}' \
+                --apply-to queues
+              if [[ "$?" == "0" ]]; then
+                echo "Policy applied successfully!"
+              else
+                echo "Error applying policies!"
+              fi
               rabbitmqctl --longnames -n rabbit@rabbitmq-0.rabbitmq-headless.{{ rabbitmq_namespace }}.svc.cluster.local \
                 list_policies
